---
# use pip version of ansible and shade only
# for ubuntu14 use  - [service, ssh, restart]
- name: Create a new instance 
  os_server:
    state: present
    name: "{{ansible_vm}}"
    image: "{{image_id}}"
    flavor: "{{flavor_id}}"
    nics:
     - net-name: "{{net_name}}"
    floating_ip_pools: "{{ext_net}}"
    userdata: |
            #cloud-config
            debug: true
            disable_root: false
            ssh_pwauth: True
            sudo: ALL=(ALL) NOPASSWD:ALL
            runcmd:
               - [sed, -i, 's/^PermitRootLogin.*/PermitRootLogin yes/g', /etc/ssh/sshd_config]
               - [systemctl, restart, sshd]
            chpasswd:
              list: |
                   root:{{vm_root_passwd}}
              expire: False
  register: ansible_vm

- add_host:
    name: ansible_vm
    ansible_host: "{{ansible_vm.server.public_v4}}"
    ansible_user: root
    ansible_password: "{{vm_root_passwd}}"
    ansible_python_interpreter: "{{ansible_python_ver_path}}"
    ansible_become: true

- name: Wait 300 seconds for port 22 to become open on the host
  wait_for:
     host: "{{ansible_vm.server.public_v4}}"
     port: 22
     sleep: 30
