---
# use pip version of ansible and shade only
- name: Create a new instance 
  os_server:
    state: present
    name: "{{ansible_vm}}"
    image: "{{image_id}}"
    flavor: "{{flavor_id}}"
    nics:
     - net-name: "{{net_name}}"
    floating_ip_pools: "{{ext_net}}"
    userdata: |
            #cloud-config
            debug: true
            user: "{{vm_ssh_user}}"
            disable_root: false
            ssh_pwauth: True
            sudo: ALL=(ALL) NOPASSWD:ALL
            chpasswd:
              list: |
                   root:{{vm_root_passwd}}
                   {{vm_ssh_user}}:{{vm_ssh_passwd}}
              expire: False
  register: ansible_vm
- add_host:
    name: ansible_vm
    ansible_host: "{{ansible_vm.server.public_v4}}"
    ansible_user: "{{vm_ssh_user}}"
    ansible_password: "{{vm_ssh_passwd}}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true

- name: Wait 300 seconds for port 22 to become open on the host
  wait_for:
     host: "{{ansible_vm.server.public_v4}}"
     port: 22
     sleep: 30
