---
- include: ubuntu.yml
  when: ansible_os_family=="Debian"

- include: redhat.yml
  when: ansible_os_family=="RedHat"

- include: suse.yml
  when: ansible_os_family=="Suse"

- name: create vnc folder
  file:
    path: /root/.vnc
    state: directory
    mode: 0755

- name: set vncpassword
  shell: echo c6j6pqwe | vncpasswd -f > /root/.vnc/passwd

- name: set permission for vncpasswd file
  file:
    path: /root/.vnc/passwd
    mode: 0600

- name: enable vncserver service
  systemd:
    name: vncserver.service
    enabled: yes

- name: start vnc server
  systemd: state=started name=vncserver.service
