---
- name: install tiger vnc server
  yum:
    name: tigervnc-server

- name: copy vncserver config  file
  copy:
    src: "{{ role_path }}/files/vncserver.service"
    dest: /etc/systemd/system/vncserver.service

