---
- name: check for v100 GPU
  shell : lspci -nv | grep 10de:1db1
  register: v100_output
  ignore_errors: True

- name: set the nvidia_url
  set_fact: 
    nvidia_url: "{{ nvidia_ubuntu_v100_url  }}"
  when: ansible_os_family=="Debian" and v100_output.rc==0

- name: set the nvidia_url
  set_fact: 
    nvidia_url: "{{ nvidia_rhel_v100_url  }}"
  when: ansible_os_family=="RedHat" and v100_output.rc==0

- name: check for k80 GPU
  shell : lspci -nv | grep 10de:102d
  register: k80_output
  ignore_errors: True
 
- name: set the nvidia_url
  set_fact: 
    nvidia_url: "{{ nvidia_ubuntu_k80_url  }}"
  when: ansible_os_family=="Debian" and k80_output.rc==0

- name: check for P100 GPU
  shell : lspci -nv | grep 10de:15f9
  register: p100_output
  ignore_errors: True

- name: set the nvidia_url
  set_fact: 
    nvidia_url: "{{ nvidia_ubuntu_p100_url  }}"
  when: ansible_os_family=="Debian" and p100_output.rc==0

- include: ubuntu.yml
  when: ansible_os_family=="Debian"

- include: redhat.yml
  when: ansible_os_family=="RedHat"

- include: suse.yml
  when: ansible_os_family=="Suse"
