---
- name: copy jar files to java folder
  copy:
    src: "{{ item }}"
    dest: /usr/lib64/jvm/java-1.8.0-ibm-1.8.0/jre/lib
    mode: 0755
  with_fileglob:
    - "{{ role_path }}/files/*"
  when: ansible_os_family=="Suse"

- name: copy jar files to java folder
  copy:
    src: "{{ item }}"
    dest: /usr/lib/jvm/java-1.8.0-ibm-1.8.0.4.5-1jpp.1.el7_3.ppc64le/jre/lib
    mode: 0755
  with_fileglob:
    - "{{ role_path }}/files/*"
  when: ansible_os_family=="RedHat" and ansible_distribution_version=="7.3"

- name: copy jar files to java folder for centos 7.3
  copy:
    src: "{{ item }}"
    dest: /usr/lib/jvm/java-1.8.0-ibm-1.8.0.4.5-1jpp.1.el7_3.ppc64le/jre/lib
    mode: 0755
  with_fileglob:
    - "{{ role_path }}/files/*"
  when: ansible_distribution=="CentOS" and ansible_distribution_release=="AltArch" and ansible_distribution_version=="7.3.1611"

- name: copy jar files to java folder
  copy:
    src: "{{ item }}"
    dest: /usr/lib/jvm/java-1.8.0-ibm-1.8.0.5.5-1jpp.2.el7.ppc64le/jre/lib
    mode: 0755
  with_fileglob:
    - "{{ role_path }}/files/*"
  when: ansible_os_family=="RedHat" and ansible_distribution_version=="7.4"
