---
- name: copy pkg list file
  copy:
    src: "{{ role_path }}/files/systemui_packages.list"
    dest: /tmp/systemui_packages.list

- name: install gnome packages
  shell: yum install -y $(cat /tmp/systemui_packages.list) 
