---
- name: install docker and compose
  apt: 
    name:
     - docker.io
     - docker-compose

- name: copy nvidia-docker  deb files
  copy:
    src: "{{ role_path }}/files/nvidia-docker_1.0.1-1_ppc64el.deb"
    dest: /tmp/nvidia-docker_1.0.1-1_ppc64el.deb

- name: install nvidia-docker deb
  apt: deb="/tmp/nvidia-docker_1.0.1-1_ppc64el.deb"

- name: delete nvidia-docker deb
  file: path=/tmp/nvidia-docker_1.0.1-1_ppc64el.deb state=absent

- name: install python-pip
  apt: name=python-pip

- name: update pip
  command: pip install --upgrade pip

- name: install dockerdevice through pip
  pip: 
    name:
      - docker-py
      - dockerdevice

- name: create nvidia-docker volume
  command: docker volume create --name=nvidia_driver_390.46 --driver=nvidia-docker
