---
- name: update swap in cloud.cfg
  blockinfile:
    path: /etc/cloud/cloud.cfg
    insertafter: EOF 
    marker: "### swap mount ###"
    block: |
       mounts:
         - [ vda, none, swap, sw, 0, 0 ]
