---
- name: Add xl compilers repo
  zypper_repository:
    name: ibm-xl-compiler
    repo: 'http://public.dhe.ibm.com/software/server/POWER/Linux/xl-compiler/eval/ppc64le/sles12/'
    state: present

- name: Install xlc
  zypper:
    name: 
      - xlf
      - xlc
    state: latest
    update_cache: yes
