---
- name: restart ceilometer-agent-compute
  service: name=ceilometer-agent-compute state=restarted enabled=yes

- name: restart nova-compute
  service: name=nova-compute state=restarted enabled=yes
