---
- name: include all cloud-init roles
  include_role:  
    name : cloud-init/swap-add

- include_role:
    name: cloud-init/manage-etc-hosts

- include_role:
    name: cloud-init/set-hostname-always
    
- include_role:
    name: cloud-init/datasource

- include_role:
    name: cloud-init/clean-up
